# Generated by Django 5.2 on 2025-04-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conteudo',
            old_name='dataLancamento',
            new_name='data_lancamento',
        ),
    ]
